"""Collect every placeholder in the database into NEEDS_CLAIMS.md.

    python tools/needs_claims.py
    python tools/needs_claims.py --db scratch.db --out /dev/stdout

A placeholder is correct output. It marks the exact sentence that is waiting
on a page number, and this tool turns the set of them into a worklist grouped
by the source that would settle each one.

Grouping is by the source the placeholder names, or by keyword when it names
none. A placeholder that lands in "unassigned" is not a failure of the writer;
it is a question nothing on the shelf can answer yet, and those are the ones
worth reading first.
"""

from __future__ import annotations

import argparse
import re
import sqlite3
import sys
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PLACEHOLDER = re.compile(r"\[\[NEEDS CLAIM:\s*(.*?)\]\]", re.S)

# What a placeholder's wording implies about where the answer lives.
ROUTES = [
    (re.compile(r"\birshad\b|al-?mufid", re.I), "SRC-IRS-003",
     "al-Mufid, Kitab al-Irshad, tr. Howard - the chapter on Musa al-Kazim"),
    (re.compile(r"al-?tabari|\bchronicle\b", re.I), "SRC-TAB-AR",
     "al-Tabari, Ta'rikh (Arabic, OpenITI) - the annalistic notices"),
    (re.compile(r"al-?kafi|kulayni|\bchain", re.I), "SRC-KAF-001",
     "al-Kulayni, al-Kafi vol. 1 - the isnads and the sect labels in them"),
    (re.compile(r"uyun|al-?rida|al-?saduq", re.I), "SRC-UYU-001",
     "Ibn Babawayh, 'Uyun Akhbar al-Rida"),
    (re.compile(r"qarashi", re.I), "SRC-QAR-001",
     "al-Qarashi, The Life of Imam Musa bin Ja'far al-Kazim"),
    (re.compile(r"\bwaqifa\b|\bsect\b|modarressi", re.I), "SRC-MOD-001",
     "NOT ON HAND. Modarressi, Crisis and Consolidation, is the standing "
     "treatment of the Waqifa. Register a copy by hand."),
    (re.compile(r"distance|road|route|mile|farsakh|yaqut", re.I), "SRC-YAQ-001",
     "NOT USABLE. The Wustenfeld Yaqut fetched from archive.org has broken "
     "OCR. A distance needs a readable geography."),
]


def route(text: str) -> tuple[str, str]:
    for pattern, key, where in ROUTES:
        if pattern.search(text):
            return key, where
    return "unassigned", ("Nothing on the shelf obviously answers this. Decide "
                          "which volume would, register it, then write the row.")


def main() -> int:
    sys.stdout.reconfigure(encoding="utf-8")
    ap = argparse.ArgumentParser(description="build NEEDS_CLAIMS.md")
    ap.add_argument("--db", default=str(ROOT / "claims.db"))
    ap.add_argument("--out", default=str(ROOT / "NEEDS_CLAIMS.md"))
    a = ap.parse_args()

    conn = sqlite3.connect(a.db)
    conn.row_factory = sqlite3.Row
    groups: dict[tuple[str, str], list[tuple[str, int, str]]] = defaultdict(list)
    total = 0
    for row in conn.execute("SELECT * FROM slide ORDER BY post_id, position"):
        for m in PLACEHOLDER.finditer(row["body"]):
            need = " ".join(m.group(1).split())
            groups[route(need)].append((row["post_id"], row["position"], need))
            total += 1

    lines = [
        "# Needs claims",
        "",
        "Generated by `python tools/needs_claims.py`. Do not edit by hand: edit",
        "the essay, reload it, and regenerate.",
        "",
        f"**{total} placeholders** are waiting on a source.",
        "",
        "Each one marks a sentence that is written and cannot render. Settling",
        "one means opening the volume at the passage, reading the line, adding",
        "the row with `tools/db.py claim-add`, and marking it verified with",
        "`tools/db.py verify`. The verify step refuses to run while the source's",
        "`edition:` in sources/manifest.yaml still says TODO, so fill those in",
        "first: it is fifteen minutes of copying title pages and it unblocks",
        "everything downstream.",
        "",
    ]
    for (key, where), items in sorted(groups.items()):
        lines += [f"## {key}", "", where, ""]
        for post_id, position, need in items:
            lines.append(f"- `{post_id}` slide {position} - {need}")
        lines.append("")

    lines += [
        "## How a placeholder becomes a slide",
        "",
        "```",
        "python tools/lookup.py \"al-Sindi\" --source irshad-howard --context 1",
        "python tools/db.py claim-add --subject \"Musa b. Ja'far\" \\",
        "    --assertion \"died in the prison of al-Sindi b. Shahik\" \\",
        "    --hijri 183 --source SRC-IRS-003 \\",
        "    --locator \"p. 407\" --pillar collision",
        "python tools/db.py verify CLM-0001 --by zaki",
        "```",
        "",
        "Then replace the placeholder in the essay file with the sentence the",
        "passage supports, reload, and lint.",
        "",
    ]
    Path(a.out).write_text("\n".join(lines), encoding="utf-8")
    print(f"{total} placeholders across {len(groups)} groups -> {a.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
